### ISSUE TITLE
Cannot open old chats

### ISSUE THREAD

**Issue by HenriTUM** [benediktbluemelhuber/TUM_MGT_Chatbot#50]
<img width="1113" alt="image" src="https://github.com/benediktbluemelhuber/TUM_MGT_Chatbot/assets/116790112/22ed907e-3d34-4341-b5c1-edc4e1d2146f">

when clicking on chats on the sidebar, they are not opened. In case of direct access via link, the screenshot failure message appears

**Comment by mohanadkandil** [comment]
Could you please try again ? there was a deployment at the time u tested the app @HenriTUM

**Comment by HenriTUM** [comment]
Joo works now, thanks!

Von: mohanadkandil ***@***.***>
Antworten an: benediktbluemelhuber/TUM_MGT_Chatbot ***@***.***>
Datum: Donnerstag, 28. März 2024 um 12:04
An: benediktbluemelhuber/TUM_MGT_Chatbot ***@***.***>
Cc: Henri Zalbertus ***@***.***>, Mention ***@***.***>
Betreff: Re: [benediktbluemelhuber/TUM_MGT_Chatbot] Cannot open old chats (Issue #50)


Could you please try again ? there was a deployment at the time u tested the app @HenriTUM<https://github.com/HenriTUM>

**Comment by mohanadkandil** [comment]
Cool, anytime :)
